site_name: aiovkcom
site_url: https://konstantintogoi.github.io/aiovkcom
repo_url: https://github.com/konstantintogoi/aiovkcom
repo_name: aiovkcom
nav:
  - 'Home': index.md
  - 'Installation': installation.md
  - 'Requests': requests.md
  - 'API': api.md
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
